#服务端口号
server:
  port: 8001
#服务名称
spring:
  application:
    name: clound-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource   #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver     #mysql驱动包
#    url: jdbc:mysql://localhost:3306/springclound?useUnicode=true&characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://localhost:3306/springclound?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: lzl5536556

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lzr.springcloudtest.entities  #所有entity别名类所在包